name: Validate alerts

on:
  pull_request:
    branches:
      - main

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: instrumenta/conftest-action@master
      with:
        files: alerts/